import type { INodeProperties } from 'n8n-workflow';
import { blogIdProperty, simplifyProperty, timezoneProperty } from '../../descriptions/shared';

const RESOURCE = 'scheduledPost';

const allOperations = [
	'getAll',
	'get',
	'create',
	'update',
	'updatePartial',
	'delete',
	'getDeleted',
	'restore',
] as const;

const postIdOperations = ['get', 'delete', 'update', 'updatePartial', 'restore'] as const;

const bodyOperations = ['create', 'update'] as const;

const show = (operation: readonly string[], extra?: Record<string, string[] | boolean[]>) => ({
	show: {
		resource: [RESOURCE],
		operation: [...operation],
		...extra,
	},
});

export const scheduledPostOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: [RESOURCE] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				action: 'Create scheduled post',
				description: 'Schedule a new post for one or more networks',
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete scheduled post',
				description: 'Move a scheduled post to deleted (can be restored)',
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get scheduled post',
				description: 'Retrieve a scheduled post by ID',
			},
			{
				name: 'Get Deleted',
				value: 'getDeleted',
				action: 'Get deleted scheduled posts',
				description: 'List deleted scheduled posts for the brand',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many scheduled posts',
				description: 'Retrieve scheduled posts between two dates',
			},
			{
				name: 'Restore',
				value: 'restore',
				action: 'Restore deleted scheduled post',
				description: 'Restore a previously deleted scheduled post',
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update scheduled post',
				description: 'Replace a scheduled post with a full update',
			},
			{
				name: 'Update Partial',
				value: 'updatePartial',
				action: 'Partially update scheduled post',
				description: 'Update only the publication date of a scheduled post',
			},
		],
		default: 'getAll',
	},
];

export const scheduledPostFields: INodeProperties[] = [
	{
		...blogIdProperty({ show: { resource: [RESOURCE], operation: [...allOperations] } }),
	},
	simplifyProperty({ show: { resource: [RESOURCE], operation: ['get', 'getAll'] } }),
	{
		displayName: 'Start',
		name: 'start',
		type: 'dateTime',
		default: '',
		description:
			'Start of the date range (sent as YYYY-MM-DDTHH:mm:ss). Required unless Filter is set.',
		displayOptions: show(['getAll']),
	},
	{
		displayName: 'End',
		name: 'end',
		type: 'dateTime',
		default: '',
		description:
			'End of the date range (sent as YYYY-MM-DDTHH:mm:ss). Required unless Filter is set.',
		displayOptions: show(['getAll']),
	},
	{
		...timezoneProperty('timezone', false),
		displayOptions: show(['getAll']),
	},
	{
		displayName: 'Extended Range',
		name: 'extendedRange',
		type: 'boolean',
		default: false,
		description:
			'Whether to expand the search range by one day before and after to avoid timezone issues',
		displayOptions: show(['getAll']),
	},
	{
		displayName: 'Filter',
		name: 'filter',
		type: 'string',
		default: '',
		placeholder:
			'e.g. {"publicationDate":{"start":"2026-01-01T00:00:00","end":"2026-01-31T23:59:59"},"providers":["instagram"]}',
		description:
			'Optional JSON filter that must include publicationDate and providers, or a valid uuid (not both). When set, start/end and other query params are ignored.',
		displayOptions: show(['getAll']),
	},
	{
		displayName: 'Order By',
		name: 'orderBy',
		type: 'options',
		required: true,
		options: [
			{ name: 'Deletion Date', value: 'deletionDate' },
			{ name: 'Publish Date', value: 'publishDate' },
		],
		default: 'deletionDate',
		description: 'Field used to sort deleted posts',
		displayOptions: show(['getDeleted']),
	},
	{
		displayName: 'Order Direction',
		name: 'orderDirection',
		type: 'options',
		required: true,
		options: [
			{ name: 'Ascending', value: 'ASC' },
			{ name: 'Descending', value: 'DESC' },
		],
		default: 'DESC',
		description: 'Sort direction for deleted posts',
		displayOptions: show(['getDeleted']),
	},
	{
		displayName: 'Page',
		name: 'page',
		type: 'number',
		typeOptions: { minValue: 0 },
		default: 0,
		description: 'Page index (0-based)',
		displayOptions: show(['getDeleted']),
	},
	{
		displayName: 'Page Size',
		name: 'pageSize',
		type: 'number',
		typeOptions: { minValue: 10, maxValue: 1000 },
		default: 50,
		description: 'Number of results per page (10–1000)',
		displayOptions: show(['getDeleted']),
	},
	{
		...timezoneProperty('timezone', false),
		displayOptions: show(['getDeleted']),
	},
	{
		displayName: 'Post ID',
		name: 'postId',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'e.g. 123456789',
		description: 'Numeric ID of the scheduled post',
		displayOptions: show(postIdOperations),
	},
	{
		displayName: 'UUID',
		name: 'uuid',
		type: 'string',
		default: '',
		placeholder: 'e.g. 550e8400-e29b-41d4-a716-446655440000',
		description: 'Post UUID — required for full updates when the post is part of an approval workflow',
		displayOptions: show(['update']),
	},
	{
		displayName: 'Publication Date',
		name: 'publicationDate',
		type: 'dateTime',
		required: true,
		default: '',
		description: 'New publication date and time for the post',
		displayOptions: show(['updatePartial']),
	},
	{
		...timezoneProperty('timezone', false),
		displayOptions: show(['updatePartial']),
	},
	{
		displayName: 'Body Input Mode',
		name: 'bodyMode',
		type: 'options',
		noDataExpression: true,
		options: [
			{ name: 'Fields', value: 'fields', description: 'Build the post using node fields' },
			{ name: 'JSON', value: 'json', description: 'Provide the full request body as JSON' },
		],
		default: 'fields',
		displayOptions: show(bodyOperations),
	},
	{
		displayName: 'JSON Body',
		name: 'jsonBody',
		type: 'json',
		required: true,
		default: '{}',
		description: 'Full ScheduledPost object as JSON',
		displayOptions: show(bodyOperations, { bodyMode: ['json'] }),
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		required: true,
		typeOptions: { rows: 4 },
		default: '',
		placeholder: 'e.g. Check out our latest update',
		description: 'Post caption or text content (required by Metricool ScheduledPost)',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'] }),
	},
	{
		displayName: 'Publication Date',
		name: 'publicationDate',
		type: 'dateTime',
		required: true,
		default: '',
		description: 'When the post should be published',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'] }),
	},
	{
		...timezoneProperty('timezone', false),
		displayOptions: show(bodyOperations, { bodyMode: ['fields'] }),
	},
	{
		displayName: 'Network Names or IDs',
		name: 'networks',
		type: 'multiOptions',
		required: true,
		typeOptions: {
			loadOptionsMethod: 'getBrandNetworksForScheduledPost',
			loadOptionsDependsOn: ['blogId'],
		},
		default: [],
		description:
			'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'] }),
	},
	{
		displayName: 'Media URLs',
		name: 'mediaUrls',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		placeholder: 'e.g. https://example.com/image.png',
		description: 'Image or video URLs, one per line or comma-separated',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'] }),
	},
	{
		displayName: 'Media Alt Text',
		name: 'mediaAltText',
		type: 'string',
		typeOptions: { rows: 2 },
		default: '',
		placeholder: 'e.g. Product photo on white background',
		description: 'Alt text for media items, one per line matching Media URLs order',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'] }),
	},
	{
		displayName: 'First Comment Text',
		name: 'firstCommentText',
		type: 'string',
		default: '',
		placeholder: 'e.g. Link in bio for details',
		description: 'Text for the first comment (Instagram, Facebook, LinkedIn)',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'] }),
	},
	{
		displayName: 'Auto Publish',
		name: 'autoPublish',
		type: 'boolean',
		default: true,
		description: 'Whether to automatically publish at the scheduled time',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'] }),
	},
	{
		displayName: 'Draft',
		name: 'draft',
		type: 'boolean',
		default: false,
		description: 'Whether to save as a draft instead of scheduling for publication',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'] }),
	},
	{
		displayName: 'Shortener',
		name: 'shortener',
		type: 'boolean',
		default: false,
		description: 'Whether to enable URL shortening for links in the post',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'] }),
	},
	{
		displayName: 'Descendants JSON',
		name: 'descendantsJson',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		description: 'JSON array of thread/reply posts (descendants)',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'] }),
	},
	{
		displayName: 'Extra JSON',
		name: 'extraJson',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		description: 'Additional fields merged into the request body as JSON object',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'] }),
	},
	{
		displayName: 'Instagram Type',
		name: 'instagramType',
		type: 'options',
		options: [
			{ name: 'Post', value: 'POST' },
			{ name: 'Reel', value: 'REEL' },
			{ name: 'Story', value: 'STORY' },
			{ name: 'Trial Reel', value: 'TRIAL_REEL' },
		],
		default: 'POST',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['instagram'] }),
	},
	{
		displayName: 'Show Reel On Feed',
		name: 'instagramShowReelOnFeed',
		type: 'boolean',
		default: true,
		description: 'Whether to also show the Instagram reel on the profile feed',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['instagram'] }),
	},
	{
		displayName: 'Instagram Collaborators',
		name: 'instagramCollaborators',
		type: 'string',
		default: '[]',
		placeholder: 'e.g. [{"username":"creator","deleted":false}]',
		description:
			'JSON array of Instagram collaborator tags (`username`, optional `deleted`) per Metricool InstagramCollaboratorTag',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['instagram'] }),
	},
	{
		displayName: 'Facebook Type',
		name: 'facebookType',
		type: 'options',
		options: [
			{ name: 'Post', value: 'POST' },
			{ name: 'Reel', value: 'REEL' },
			{ name: 'Story', value: 'STORY' },
		],
		default: 'POST',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['facebook'] }),
	},
	{
		displayName: 'Facebook Title',
		name: 'facebookTitle',
		type: 'string',
		default: '',
		placeholder: 'e.g. Spring campaign launch',
		description: 'Optional title for Facebook posts or reels',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['facebook'] }),
	},
	{
		displayName: 'TikTok Privacy',
		name: 'tiktokPrivacy',
		type: 'options',
		options: [
			{ name: 'Public To Everyone', value: 'PUBLIC_TO_EVERYONE' },
			{ name: 'Mutual Follow Friends', value: 'MUTUAL_FOLLOW_FRIENDS' },
			{ name: 'Follower Of Creator', value: 'FOLLOWER_OF_CREATOR' },
			{ name: 'Self Only', value: 'SELF_ONLY' },
		],
		default: 'PUBLIC_TO_EVERYONE',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['tiktok'] }),
	},
	{
		displayName: 'Disable Comments',
		name: 'tiktokDisableComment',
		type: 'boolean',
		default: false,
		description: 'Whether to disable comments on the TikTok post',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['tiktok'] }),
	},
	{
		displayName: 'Disable Duet',
		name: 'tiktokDisableDuet',
		type: 'boolean',
		default: false,
		description: 'Whether to disable Duet on the TikTok post',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['tiktok'] }),
	},
	{
		displayName: 'Disable Stitch',
		name: 'tiktokDisableStitch',
		type: 'boolean',
		default: false,
		description: 'Whether to disable Stitch on the TikTok post',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['tiktok'] }),
	},
	{
		displayName: 'TikTok Title',
		name: 'tiktokTitle',
		type: 'string',
		default: '',
		placeholder: 'e.g. Behind the scenes',
		description: 'Title shown on the TikTok post',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['tiktok'] }),
	},
	{
		displayName: 'Commercial Content Third Party',
		name: 'tiktokCommercialThirdParty',
		type: 'boolean',
		default: false,
		description: 'Whether the post promotes a third-party brand',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['tiktok'] }),
	},
	{
		displayName: 'Commercial Content Own Brand',
		name: 'tiktokCommercialOwnBrand',
		type: 'boolean',
		default: false,
		description: 'Whether the post promotes your own brand',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['tiktok'] }),
	},
	{
		displayName: 'Auto Add Music',
		name: 'tiktokAutoAddMusic',
		type: 'boolean',
		default: false,
		description: 'Whether to automatically add music recommended by TikTok',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['tiktok'] }),
	},
	{
		displayName: 'YouTube Title',
		name: 'youtubeTitle',
		type: 'string',
		default: '',
		required: true,
		placeholder: 'e.g. Product demo walkthrough',
		description: 'Title of the YouTube video or short',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['youtube'] }),
	},
	{
		displayName: 'YouTube Type',
		name: 'youtubeType',
		type: 'options',
		options: [
			{ name: 'Video', value: 'video' },
			{ name: 'Short', value: 'short' },
		],
		default: 'video',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['youtube'] }),
	},
	{
		displayName: 'YouTube Privacy',
		name: 'youtubePrivacy',
		type: 'options',
		options: [
			{ name: 'Public', value: 'public' },
			{ name: 'Unlisted', value: 'unlisted' },
			{ name: 'Private', value: 'private' },
		],
		default: 'public',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['youtube'] }),
	},
	{
		displayName: 'Made For Kids',
		name: 'youtubeMadeForKids',
		type: 'boolean',
		default: false,
		description: 'Whether the video is made for kids',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['youtube'] }),
	},
	{
		displayName: 'YouTube Tags',
		name: 'youtubeTags',
		type: 'string',
		default: '',
		placeholder: 'e.g. marketing, tutorial, product',
		description: 'Comma or newline-separated tags',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['youtube'] }),
	},
	{
		displayName: 'YouTube Category',
		name: 'youtubeCategory',
		type: 'string',
		default: '',
		placeholder: 'e.g. 22',
		description: 'YouTube category ID',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['youtube'] }),
	},
	{
		displayName: 'YouTube Playlist ID',
		name: 'youtubePlaylistId',
		type: 'string',
		default: '',
		placeholder: 'e.g. PLxxxxxxxx',
		description: 'Playlist to add the video to',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['youtube'] }),
	},
	{
		displayName: 'Pinterest Board Name or ID',
		name: 'pinterestBoardId',
		type: 'options',
		typeOptions: {
			loadOptionsMethod: 'getPinterestBoards',
			loadOptionsDependsOn: ['blogId'],
		},
		default: '',
		required: true,
		description: 'Pinterest board to pin to. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['pinterest'] }),
	},
	{
		displayName: 'Pin Title',
		name: 'pinterestPinTitle',
		type: 'string',
		default: '',
		placeholder: 'e.g. Summer lookbook',
		description: 'Title of the Pinterest pin',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['pinterest'] }),
	},
	{
		displayName: 'Pin Link',
		name: 'pinterestPinLink',
		type: 'string',
		default: '',
		placeholder: 'e.g. https://example.com/landing',
		description: 'Destination URL for the pin',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['pinterest'] }),
	},
	{
		displayName: 'Pin New Format',
		name: 'pinterestNewFormat',
		type: 'boolean',
		default: false,
		description: 'Whether to use the newer Pinterest pin format',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['pinterest'] }),
	},
	{
		displayName: 'LinkedIn Type',
		name: 'linkedinType',
		type: 'options',
		options: [
			{ name: 'Post', value: 'post' },
			{ name: 'Poll', value: 'poll' },
		],
		default: 'post',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['linkedin'] }),
	},
	{
		displayName: 'LinkedIn Poll',
		name: 'linkedinPoll',
		type: 'json',
		default: '{}',
		description:
			'Required when LinkedIn Type is Poll. ScheduledPostLinkedinPoll: question, options[{text}], settings (e.g. duration).',
		displayOptions: show(bodyOperations, {
			bodyMode: ['fields'],
			networks: ['linkedin'],
			linkedinType: ['poll'],
		}),
	},
	{
		displayName: 'Document Title',
		name: 'linkedinDocumentTitle',
		type: 'string',
		default: '',
		placeholder: 'e.g. Q2 results overview',
		description: 'Title used when publishing images as a LinkedIn document',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['linkedin'] }),
	},
	{
		displayName: 'Publish Images As PDF',
		name: 'linkedinPublishImagesAsPDF',
		type: 'boolean',
		default: false,
		description: 'Whether to publish image attachments as a PDF document on LinkedIn',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['linkedin'] }),
	},
	{
		displayName: 'Preview Included',
		name: 'linkedinPreviewIncluded',
		type: 'boolean',
		default: true,
		description: 'Whether to include a link preview on the LinkedIn post',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['linkedin'] }),
	},
	{
		displayName: 'Reply Settings',
		name: 'twitterReplySettings',
		type: 'string',
		default: '',
		placeholder: 'e.g. following',
		description: 'Who can reply to the post on X',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['twitter'] }),
	},
	{
		displayName: 'Post Type',
		name: 'twitterType',
		type: 'string',
		default: '',
		description: 'X post type (e.g. post, poll)',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['twitter'] }),
	},
	{
		displayName: 'X Poll',
		name: 'twitterPoll',
		type: 'json',
		default: '{}',
		description:
			'Required when Post Type is poll. ScheduledPostTwitterPoll: options[{text}], settings (e.g. durationMinutes).',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['twitter'] }),
	},
	{
		displayName: 'Post Languages',
		name: 'blueskyLanguages',
		type: 'string',
		default: '',
		description: 'ISO language codes, comma or newline-separated',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['bluesky'] }),
	},
	{
		displayName: 'Country Codes',
		name: 'threadsCountryCodes',
		type: 'string',
		default: '',
		description: 'Allowed country codes for Threads geo-restriction, comma or newline-separated',
		displayOptions: show(bodyOperations, { bodyMode: ['fields'], networks: ['threads'] }),
	},
	{
		displayName: 'GBP Type',
		name: 'gmbType',
		type: 'string',
		default: '',
		description: 'Google Business Profile post type for ScheduledPostGmbData.type',
		displayOptions: show(bodyOperations, {
			bodyMode: ['fields'],
			networks: ['googleBusinessProfile'],
		}),
	},
];
